version: '3.1'
services:
    mysql:
        image: mysql
        ports:
            - '3306:3306'
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: test_db
            MYSQL_USER: test
            MYSQL_PASSWORD: 1234
        volumes:
            - ./data:/var/lib/mysql
