version: '3.1'
services:
    postgres:
        image: postgres
        ports:
            - '5432:5432'
        restart: always
        environment:
            POSTGRES_USER: test
            POSTGRES_PASSWORD: 1234
            POSTGRES_DB: test_db
